name: Android testers CI
on:
  push:
    branches: [testers]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.0'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test